###
GET http://localhost:3200/
###
POST http://localhost:3200/api/poblacion/subir/ HTTP/1.1
Content-Type: application/json

{
    "id_poblacion": 2,
    "nombre": "Docentes"
}
###
GET http://localhost:3200/api/poblacion/poblaciones/

###
POST http://localhost:3200/api/admin/login/ HTTP/1.1
Content-Type: application/json

{
    "id_administrador": 2,
    "correo": "joferrer@ufps.edu.co",
    "contrasena": "qwerrt"
}
###
GET http://localhost:3200/api/admin/registrados

###
DELETE http://localhost:3200/api/admin/eliminar/1 HTTP/1.1

###
GET http://localhost:3200/api/encuesta/encuestas
###
GET http://localhost:3200/api/encuesta/encuestas/1
###
GET http://localhost:3200/api/encuesta/encuestas/encuesta/1
###
POST http://localhost:3200/api/encuesta/publicar/9 HTTP/1.1
Content-Type: application/json

{
    "id_encuesta": 0,
    "nombre": "Encuesta de nivel de satisfacción en la materia de AYD",
    "porcentaje": 0,
    "id_poblacion": 0
}

###
POST http://localhost:3200/api/encuesta/publicar/110 HTTP/1.1
Content-Type: application/json

{
    "id_encuesta": 0,
    "nombre": "Encuesta de nivel de satisfacción en la materia de AYD",
    "porcentaje": 0,
    "id_poblacion": 0
}
###
GET http://localhost:3200/api/pregunta/preguntas
###
GET http://localhost:3200/api/pregunta/preguntas/1
###
POST http://localhost:3200/api/pregunta/agregarpregunta/1 HTTP/1.1
Content-Type: application/json

{
    "id_pregunta": 0,
    "enunciado": "Buena",
    "tipo": 0,
    "id_encuesta": 0
}

###
DELETE http://localhost:3200/api/pregunta/eliminar/1



###
GET http://localhost:3200/api/opcion/opciones


###
POST http://localhost:3200/api/opcion/opciones/1 HTTP/1.1
Content-Type: application/json

{
    "id_opcion": 0,
    "texto": "Buena",
    "id_pregunta": 0
}


###
GET http://localhost:3200/api/encuestado/mostrar/11

###
POST http://localhost:3200/api/encuestado/registrar/11 HTTP/1.1
Content-Type: application/json

{
    "id_encuestado": 0,
    "correo": "nelsonbeltran@ufps.edu.co",
    "id_poblacion": 0
}
